---
- name: Remove old versions of docker if present
  package:
    name:
      - docker
      - docker-engine
      - docker.io
      - containerd
    state: absent

- name: Install docker dependencies
  apt:
    update_cache: true
    name:
      - apt-transport-https
      - ca-certificates
      - gnupg2
    state: present

- name: Add Docker apt key
  apt_key:
    url: "{{ docker_repo_address }}/gpg"
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    state: present
    validate_certs: "{{ docker_repo_valid_ssl }}"
  register: add_repository_key
  ignore_errors: "{{ docker_apt_ignore_key_error }}"

- name: Ensure curl is present (on older systems without SNI)
  package: name=curl state=present
  when: add_repository_key is failed

- name: Add Docker apt key (alternative for older systems without SNI)
  shell: >
    set -o pipefail;
    curl {% if not docker_repo_valid_ssl %}-k{% endif %} -sSL {{ docker_repo_address }}/gpg | sudo apt-key add -
  args:
    warn: false
  when: add_repository_key is failed

- name: Define release channel to use
  set_fact:
    docker_release: "{% if docker_enable_test %}test{% elif docker_enable_edge %}edge{% else %}stable{% endif %}"

- name: Add Docker repository
  apt_repository:
    repo: >-
      deb [arch={{ (ansible_architecture == 'x86_64') | ternary('amd64', ansible_architecture) }}]
      {{ docker_repo | regex_replace("/$", "") }}/{{ ansible_distribution | lower }}
      {{ ansible_distribution_release }} {{ docker_release }}
    state: present
